### ISSUE TITLE
Four character-related tests fail on Windows, but not Linux

### ISSUE THREAD

**Issue by jamesrhester** [jamesrhester/pycifrw#1]
See below
```
======================================================================
FAIL: testLongStringInOut (__main__.FileWriteTestCase)
Test writing long string in and out
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\users\jxh\software\pycifrw\TestPyCIFRW.py", line 665, in testLongStringInOut
    self.failUnless(compstring == self.cf['_item_4'])
AssertionError: False is not true

======================================================================
FAIL: testLoopStringInOut (__main__.FileWriteTestCase)
Test writing in and out string loop data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\users\jxh\software\pycifrw\TestPyCIFRW.py", line 704, in testLoopStringInOut
    self.failUnless(compstringa==compstringb and compstringa==compstringc)
AssertionError: False is not true

======================================================================
FAIL: testPrefixProtocol (__main__.FileWriteTestCase)
Test that pathological strings round-trip correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\users\jxh\software\pycifrw\TestPyCIFRW.py", line 761, in testPrefixProtocol
    self.assertEqual(in_emb['tough_one']['_data_embedded'],cif_as_text)
AssertionError: 'CIF:> \\\\\r\nCIF:> #\\#CIF_2.0\r\nCIF:> [3678 chars] \'"' != '#\\#CIF_2.0\n\n##########################[2794 chars] \'"'
Diff is 9898 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: testSemiWhiteSpace (__main__.FileWriteTestCase)
Test that white space in a semicolon string is preserved
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\users\jxh\software\pycifrw\TestPyCIFRW.py", line 680, in testSemiWhiteSpace
    self.failUnless(self.cf['_item_sws']==self.df['_item_sws'])
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by jamesrhester** [comment]
Now the project is on Github this should be captured using CI.

**Comment by jamesrhester** [comment]
CI gives no failures on Windows platforms any more.
