### ISSUE TITLE
Error in CifFile when running CIF-Ontology/dic2owl

### ISSUE THREAD

**Issue by stuchalk** [jamesrhester/pycifrw#3]
I installed locally dic2owl (pip install -e dic2owl tool from the CIF-Ontology repo) and I get the following error trying to convert the cif core dictionary (v 2.4.5).

```
(CIF-ontology) n00002621@UNF-TX261G677X CIF-ontology % dic2owl ~/Desktop/cif\ dictionaries/cif_core.dic    
cif_core.dic2.4.5 is a DDL1 dictionary
Traceback (most recent call last):
  File "/Users/n00002621/.local/share/virtualenvs/CIF-ontology-CRLssc5_/bin/dic2owl", line 8, in <module>
    sys.exit(main())
  File "/Users/n00002621/PycharmProjects/CIF-ontology/dic2owl/dic2owl/cli.py", line 87, in main
    dic2owl_run(dicfile=args.dicfile, ttlfile=args.ttlfile)
  File "/Users/n00002621/PycharmProjects/CIF-ontology/dic2owl/dic2owl/dic2owl.py", line 272, in main
    onto = gen.generate()
  File "/Users/n00002621/PycharmProjects/CIF-ontology/dic2owl/dic2owl/dic2owl.py", line 117, in generate
    self._add_item(item)
  File "/Users/n00002621/PycharmProjects/CIF-ontology/dic2owl/dic2owl/dic2owl.py", line 128, in _add_item
    self._add_data_value(item)
  File "/Users/n00002621/PycharmProjects/CIF-ontology/dic2owl/dic2owl/dic2owl.py", line 178, in _add_data_value
    name = item["_definition.id"]
  File "/Users/n00002621/.local/share/virtualenvs/CIF-ontology-CRLssc5_/lib/python3.10/site-packages/CifFile/CifFile_module.py", line 269, in __getitem__
    raise KeyError("%s not found" % dataname)
KeyError: '_definition.id not found'
```

Am I doing this wrong or is this a bug?  I tried the electron density dictionary also and got the same error.
Any help very much appreciated.

**Comment by jamesrhester** [comment]
This happened because dic2owl expects DDLm versions of the dictionary. The core dictionary has just had a release, which unfortunately has not made it onto the main IUCr page yet, but you can access it via https://doi.org/10.1107/cifdic_000002.

The development versions (i.e. DDLm) are all available in the COMCIFS repositories https://github.com/COMCIFS.

**Comment by stuchalk** [comment]
Thanks for orienting me correctly on this.  I have now downloaded the ddlm dictionaries that are available and have now run across another error, which is a dic2owl error.  I will post it as an issue on the CIF_Ontology repo so I will close this issue.
